### PR TITLE
Added bootstrap and fixed progress bar animation

### PR DESCRIPTION
**Pull request by Ricardonacif**
I've just added Bootstrap and corrected the progress bar class to fix it's animation while uploading.

Thanks,

### CODE REVIEW

**Comment by 5minpause** [comment]
Looks good. Let me do a quick check for this in the next few days. Then I'll merge.
Thank you for taking the time!

**Comment by Ricardonacif** [comment]
Thank you for creating the tutorial!

**Comment by 5minpause** [comment]
You're very welcome. Your words mean very much to me.

**Comment by 5minpause** [comment]
Thank you. Everything works and looks well. Thanks for taking care of the progress bar.

**Pull request merged**
